# Generated by Django 6.0 on 2025-12-29 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_registration_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sponsor_details',
            field=models.TextField(blank=True, help_text='Additional details about the sponsorship', null=True, verbose_name='Sponsor Details (Optional)'),
        ),
        migrations.AddField(
            model_name='student',
            name='sponsor_name',
            field=models.CharField(blank=True, help_text='e.g., Hon. MP Name, Company Name, etc.', max_length=200, null=True, verbose_name='Sponsor Name (Optional)'),
        ),
        migrations.AddField(
            model_name='student',
            name='sponsorship_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount sponsored by sponsor', max_digits=10, null=True, verbose_name='Sponsorship Amount (KES)'),
        ),
        migrations.AddField(
            model_name='student',
            name='sponsorship_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sponsorship Date'),
        ),
        migrations.AddField(
            model_name='student',
            name='sponsorship_source',
            field=models.CharField(choices=[('cdf', 'CDF Fund'), ('mp', 'Member of Parliament'), ('other', 'Other Sponsor')], default='cdf', max_length=20, verbose_name='Sponsorship Source'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ward',
            field=models.CharField(choices=[('Nyangores', 'Nyangores'), ('Sigor', 'Sigor'), ('Chebunyo', 'Chebunyo'), ('Siongiroi', 'Siongiroi'), ('kongasis', 'kongasis')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['sponsorship_source'], name='students_st_sponsor_9a851d_idx'),
        ),
    ]
