# Generated by Django 6.0 on 2026-04-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_students_st_ward_b78799_idx_students_st_ward_id_28afd1_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_ward_id_28afd1_idx',
            old_name='students_st_ward_b78799_idx',
        ),
    ]
