# Generated by Django 6.0 on 2026-01-08 13:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('student_allocation', 'Student Allocation Report'), ('financial_summary', 'Financial Summary Report'), ('ward_distribution', 'Ward Distribution Report'), ('mp_sponsorship', 'MP Sponsorship Report'), ('performance', 'Performance Analytics'), ('compliance', 'Compliance Report'), ('custom', 'Custom Report')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('text', 'Text')], default='csv', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/')),
                ('file_size', models.IntegerField(default=0)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('generation_started', models.DateTimeField(auto_now_add=True)),
                ('generation_completed', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_count', models.IntegerField(default=0)),
                ('pending_count', models.IntegerField(default=0)),
                ('mp_sponsored_count', models.IntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('recurrence', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reports.report')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('student_allocation', 'Student Allocation Report'), ('financial_summary', 'Financial Summary Report'), ('ward_distribution', 'Ward Distribution Report'), ('mp_sponsorship', 'MP Sponsorship Report'), ('performance', 'Performance Analytics'), ('compliance', 'Compliance Report'), ('custom', 'Custom Report')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('day_of_week', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('scheduled_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('email_recipients', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('keep_last_n', models.IntegerField(default=10)),
                ('auto_delete_old', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('student', 'Student Report Template'), ('financial', 'Financial Report Template'), ('ward', 'Ward Report Template'), ('mp', 'MP Sponsorship Template'), ('standard', 'Standard Template')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='report_templates/')),
                ('header_html', models.TextField(blank=True, null=True)),
                ('footer_html', models.TextField(blank=True, null=True)),
                ('css_styles', models.TextField(blank=True, null=True)),
                ('default_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('text', 'Text')], default='csv', max_length=10)),
                ('include_logo', models.BooleanField(default=True)),
                ('include_charts', models.BooleanField(default=True)),
                ('include_summary', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'report_type'], name='reports_rep_status_6f5566_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by', 'created_at'], name='reports_rep_generat_b60f00_idx'),
        ),
        migrations.AddIndex(
            model_name='reportlog',
            index=models.Index(fields=['report', 'timestamp'], name='reports_rep_report__750416_idx'),
        ),
    ]
