# Generated by Django 6.0 on 2026-04-03 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_student_sponsor_details_student_sponsor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstituencyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.IntegerField(default=2026, unique=True)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remaining_budget', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Nyangores', 'Nyangores'), ('Sigor', 'Sigor'), ('Chebunyo', 'Chebunyo'), ('Siongiroi', 'Siongiroi'), ('kongasis', 'kongasis')], max_length=50, unique=True)),
                ('total_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('financial_year', models.IntegerField(default=2026)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='students.student')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='bursaries.ward')),
            ],
        ),
    ]
